<?php

#######DEFINIÇÕES DO SISTEMA

//DEFINE O NOME DO SITE
define('NOMESITE','site');

//DEFINE TITULO DA PÁGINA
define('DESCSITE','SISTEMA DE ATENDIMENTO '.NOMESITE);

//DEFINE A URL ONDE O SISTEMA ESTÁ INSTALADO
define('__BASEURL__','');



#######DEFINIÇÕES DE BANCOS DE DADOS

//PREFIXO DAS TABELAS NO BANCO DE DADOS
define('__BDPREFIX__','');
//SERVIDOR DO BANCO DE DADOS
define('BDHOST','localhost');
//USUÁRIO DO BANCO DE DADOS
define('BDUSER','root');
//SENHA DO BANCO DE DADOS
define('BDPASS','');
//NOME DA TABELA DO BANCO DE DADOS
define('BDNAME','chat');
